accelerate launch seq2seq.py --num_machines 1 --num_processes 2 \
--mixed_precision bf16 \
--constrained_generation \
--train_tsvs dataset/italian/train.tsv \
--dev_tsvs dataset/italian/dev.tsv \
--test_tsvs dataset/italian/test_new.tsv \
--num_beams 3 \
--num_return_sequences 3 \
--model_name_or_path google/t5-large \
--per_device_train_batch_size 16 \
--gradient_accumulation_steps 1 \
--per_device_eval_batch_size 8 \
--learning_rate 2e-4 \
--optim adafactor \
--lr_scheduler_type cosine \
--num_warmup_steps 500 \
--num_train_epochs 30 \
--eval_every_epochs 2 \
--max_source_length 256 \
--max_target_length 256 \
--output_dir results/ner-t5 \
--project_name ner-t5 \
--add_labels_as_tokens